# Generated by Django 4.2.2 on 2023-07-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_topics_summary_alter_topics_discriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='summary',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Название темы'),
        ),
    ]
