# Generated by Django 4.2.2 on 2023-07-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_alter_topics_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='discriptions',
        ),
        migrations.AddField(
            model_name='topics',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Описание темы'),
        ),
    ]
